### ISSUE TITLE
Update Navbar code to make it responsive.

### ISSUE THREAD

**Issue by bonniesimon** [bonniesimon/preview-mark#2]
Currently the Navbar isn't responsive enough. Provide ways to make it responsive.

**Comment by smidhunkks** [comment]
I'm taking this

**Comment by harshitsuthar77731** [comment]
assign me

**Comment by SoundaryaKhanapur** [comment]
Can I pick this up as recently implementing navbars in various projects

**Comment by bonniesimon** [comment]
Hey @smidhunkks , you can go ahead with this issue. 
I'm sorry @harshitsuthar77731 & @SoundaryaKhanapur , I want to keep this fair. So I'm choosing with a first come first serve basis. 
I'll open more issues for this repo, do keep looking.
